name: CI
on: workflow_dispatch


jobs:
  build_on_mac:
    runs-on: macOS-latest
    

    
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v1

    - name: Install Node.js and Yarn
      uses: actions/setup-node@master
      with:
        node-version: 18.16

    - name: Install dependencies
      run:  npm install

    - name: Build on MacOS
      env:
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      run: |
            export DEBUG=electron*
            security find-identity -v
            npm run build


    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/
        retention-days: 2
