name: CI
on: workflow_dispatch


jobs:
  build_on_mac:
    runs-on: macOS-latest
    

    
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v1

    - name: Install Node.js and Yarn
      uses: actions/setup-node@master
      with:
        node-version: 18.16

    - name: Install dependencies
      run: |
            export DEBUG=electron*
            npm install

    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        mac_certs: ${{ secrets.MAC_CERTS }}
        mac_certs_password: ${{ secrets.CSC_KEY_PASSWORD }}
        github_token: ${{ secrets.github_token }}
        release: false


    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/
        retention-days: 2
